### ISSUE TITLE
Is the latest version in published to npm or is there bug with callback?

### ISSUE THREAD

**Issue by sampsasaarela** [adieuadieu/alagarr#273]
Is the latest version published to the npm?

I am just wondering because of this handler:
```javascript
export const myFunction = alagarr(async (request, response) => {
  try {
    const data = await data();
    return response.json(data);
  } catch (error) {
    throw new ClientError(error);
  }
});
```

gives me a warning:

>Serverless: Warning: handler 'myFunction' returned a promise and also uses a callback!
This is problematic and might cause issues in your lambda.

Is this bug in the library or is the npm version older?

`npm install alagarr --save` install version `^1.0.0-26` and, if I try to install directly from GitHub the `dist` folder is empty, so I cant test directly from the master.

However, thanks for the great library.

**Comment by adieuadieu** [comment]
Hi @sampsasaarela — the version on npm is not the latest that's in the master branch and is missing some features/changes which haven't been. Only reason is that I haven't had the time to wrap up the changes in master branch and prepare a release.

If you install directly from this repo you'll need to run `npm run build` in the repository folder to build the files into `dist/`.

I'm not sure if the latest version of code in `master` fixes the problem about returning both a promise and a callback. Will need to check..

**Comment by hallais** [comment]
Any news? I'm facing the same issue with `async/await` in `v1.0.0-32`.
